language: csharp
mono: none
os: "linux"
group: stable
sudo: required  # use the new container-based Travis infrastructure 

services:
  - docker

before_install:
  # mssql server image
  - docker pull microsoft/mssql-server-linux
  - docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 -d microsoft/mssql-server-linux
  # rabbitmq image
  - docker pull rabbitmq
  - docker run -d --hostname my-rabbit  -p 8080:15672 rabbitmq:3-management
  # eventStore image
  - docker pull eventstore/eventstore
  - docker  run -d -it -p 2113:2113 -p 1113:1113 eventstore/eventstore

script :
  - docker build -t arthis/psychic-tribble .
  - docker run -d arthis/psychic-tribble

  


  

