// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("RessourcesLocalisees.DB")]
[assembly: AssemblyProductAttribute("RessourcesLocalisees")]
[assembly: AssemblyDescriptionAttribute("plateforme standard de developpement eclosing")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "RessourcesLocalisees.DB";
        internal const System.String AssemblyProduct = "RessourcesLocalisees";
        internal const System.String AssemblyDescription = "plateforme standard de developpement eclosing";
        internal const System.String AssemblyVersion = "1.0";
        internal const System.String AssemblyFileVersion = "1.0";
    }
}
